spring:
  config:
    import: optional:classpath:application-secrets.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

manager:
  password: ${MANAGER_PASSWORD}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration:
    access_token: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token: ${JWT_REFRESH_TOKEN_EXPIRATION}

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}